main: com.github.tmeserve.RIPPlugin
name: RIP Box
version: 1.0
description: Drops a chest at a players death location and broadcasts it
api-version: 1.18.1
author: tmeserve
website: www.github.com/tmeserve